name: github-pr-attestation
on:
  pull_request:
    types: [closed]
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Attestation
        id: attestation
        uses: show-karma/github-attestation-action@feat/attest-backfill
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          rpc-url: ${{ secrets.RPC_URL }}
          git-api: ${{ secrets.GIT_API_KEY }}
          network: optimism-goerli
          branch: main
